CREATE TABLE IF NOT EXISTS TB_FINANCIAL_HELP (
    id UUID PRIMARY KEY,
    payment_id UUID REFERENCES TB_PAYMENT(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    amount NUMERIC(8, 2) NOT NULL
);