CREATE TABLE IF NOT EXISTS TB_TUITION (
    id UUID PRIMARY KEY,
    payment_id UUID REFERENCES TB_PAYMENT(id) ON DELETE CASCADE,
    student_id UUID REFERENCES TB_STUDENT(id),
    payment_type VARCHAR(10),
    is_paid BOOLEAN NOT NULL
);