ALTER TABLE TB_TUITION DROP CONSTRAINT IF EXISTS PAYMENT_TYPE_REQUIRED_IF_IS_PAID;
ALTER TABLE TB_TUITION DROP CONSTRAINT IF EXISTS PAID_AT_REQUIRED_IF_IS_PAID;
ALTER TABLE TB_TUITION DROP COLUMN is_paid;
ALTER TABLE TB_TUITION ADD COLUMN status VARCHAR(15) NOT NULL DEFAULT 'PENDING';